name: ethereum-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - notebook
  - ipykernel
  - pandas
  - numpy
  - pyarrow
  - matplotlib
  - seaborn
  - networkx
  - pip:
      - web3
      - eth_utils
      - eth_abi





